version: 0.2
phases:
  build:
    commands:
      - echo "Running  SonarCloud Analysis"
      - mvn verify sonar:sonar -Dsonar.projectKey=dquinnie2 -Dsonar.organization=dquinnie2 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=dd5e870757e1b0319fdafba5080400c0d3100687
